/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/static_content/about.vue')['default']
    Admin_sidebar: typeof import('./src/components/sidebar/admin_sidebar.vue')['default']
    Article: typeof import('./src/components/static_content/article/index.vue')['default']
    Article_detail: typeof import('./src/components/static_content/article/article_detail/index.vue')['default']
    Article_pre: typeof import('./src/components/static_content/article/article_pre/index.vue')['default']
    Articledetail: typeof import('./src/components/articledetail.vue')['default']
    ArticleDetail: typeof import('./src/components/static_content/article/articleDetail.vue')['default']
    ArticleDetaile: typeof import('./src/components/static_content/article/articleDetaile/index.vue')['default']
    ArticleEdit: typeof import('./src/components/manage/articleEdit.vue')['default']
    ArticleManage: typeof import('./src/components/manage/articleManage.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElNav: typeof import('element-plus/es')['ElNav']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/helloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar/sidebar.vue')['default']
    Signin: typeof import('./src/components/signin/index.vue')['default']
    Style_change: typeof import('./src/components/sidebar/sidebar_components/style_change/index.vue')['default']
    Visitor_sidebar: typeof import('./src/components/sidebar/visitor_sidebar.vue')['default']
  }
}
